version: 2

init_task: &init_task
  name: Init git submodules
  command: make init
build_task: &build_task
  name: Build
  command: make test
verify_task: &verify_task
  name: Verify Google Java Format
  command: ./gradlew verGJF

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run: sudo apt-get update && sudo apt-get install -y make
      - run:
          <<: *init_task
      - run:
          <<: *verify_task
      - run:
          <<: *build_task
      - run:
          name: Cover
          command: ./gradlew check :opentelemetry-all:jacocoTestReport
      - run:
          name: Publish coverage
          command:  bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle" }}
  java9:
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - java9-gradle-{{ checksum "build.gradle" }}
      - run: sudo apt-get update && sudo apt-get install -y make
      - run:
          <<: *init_task
      - run:
          <<: *verify_task
      - run:
          <<: *build_task
      - save_cache:
          paths:
            - ~/.gradle
          key: java9-gradle-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - java9
