name: Benchmark Tags

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  sdk-benchmark:
    permissions:
      contents: write # for git push to benchmarks branch
    name: Benchmark SDK
    runs-on: oracle-bare-metal-64cpu-512gb-x86-64
    container:
      image: ubuntu:24.04@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54
    timeout-minutes: 20 # since there is only a single bare metal runner across all repos
    strategy:
      fail-fast: false
      matrix:
        tag-version:
          - v1.29.0
          - v1.30.0
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: ${{ matrix.tag-version }}

      - id: setup-java
        name: Set up Java for build
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          distribution: temurin
          java-version: 21

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Run jmh
        run: ./gradlew jmhJar
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}

      - name: Run Benchmark
        run: |
          cd sdk/trace/build
          java -jar libs/opentelemetry-sdk-trace-*-jmh.jar -rf json SpanBenchmark SpanPipelineBenchmark ExporterBenchmark

      - name: Store benchmark results
        uses: benchmark-action/github-action-benchmark@4bdcce38c94cec68da58d012ac24b7b1155efe8b # v1.20.7
        with:
          tool: 'jmh'
          output-file-path: sdk/trace/build/jmh-result.json
          gh-pages-branch: benchmarks
          github-token: ${{ secrets.GITHUB_TOKEN }}
          benchmark-data-dir-path: "benchmarks"
          auto-push: true
          ref: ${{ matrix.tag-version }}
