name: "PR Build"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-20.04
        test-java-version:
          - 8
          - 11
          - 16
          - 17
        include:
          - os: ubuntu-20.04
            test-java-version: 11
            coverage: true
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - id: setup-java-8
        name: Setup Java 8 for tests
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8
          java-package: jre
      - id: setup-java-16
        name: Setup Java 16 for tests
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16
      - id: setup-java-17
        name: Setup Java 17 for tests
        uses: actions/setup-java@v2
        with:
          # TODO(anuraaga): Switch to adopt when they release 17-ea
          distribution: zulu
          java-version: 17-ea
      - id: setup-java-11
        name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - uses: burrunan/gradle-cache-action@v1.10
        with:
          job-id: jdk${{ matrix.test-java-version }}
          remote-build-cache-proxy-enabled: false
          arguments: build --stacktrace ${{ matrix.coverage && 'jacocoTestReport' || '' }}
          properties: |
            testJavaVersion=${{ matrix.test-java-version }}
            org.gradle.java.installations.paths=${{ steps.setup-java-8.outputs.path }},${{ steps.setup-java-11.outputs.path }},${{ steps.setup-java-16.outputs.path }},${{ steps.setup-java-17.outputs.path }}
      - uses: codecov/codecov-action@v2.0.3
        if: ${{ matrix.coverage }}
      - uses: actions/upload-artifact@v2
        if: ${{ matrix.coverage }}
        with:
          name: coverage-report
          path: all/build/reports/jacoco/test/html
